// Generated by CoffeeScript 1.7.1
(function() {
  var Skipper, main;

  Skipper = (function() {
    function Skipper(skip_num) {
      this.skip_num = skip_num;
    }

    Skipper.prototype.next = function(num) {
      return find_next(num);
    };

    Skipper.prototype.find_next = function(num) {
      var count;
      count = num + 1;
      while (!(count % this.skip_num) && (count.toString().indexOf(this.skip_num.toString() !== -1))) {
        count++;
      }
      return count;
    };

    return Skipper;

  })();

  main = function() {
    var i, s3, s4, _i, _j, _results;
    console.log("=== test 3 game === ");
    s3 = new Skipper(3);
    for (i = _i = 1; _i <= 50; i = ++_i) {
      console.log("num : " + i + " > " + s3.next(i));
    }
    console.log("=== test 4 game === ");
    s4 = new Skipper(4);
    _results = [];
    for (i = _j = 1; _j <= 50; i = ++_j) {
      _results.push(console.log("num : " + i + " > " + s4.next(i)));
    }
    return _results;
  };

}).call(this);
